/*CREACION DE LA TABLA USUARIOS*/
CREATE TABLE USUARIOS (
ID_USUARIO DECIMAL(12) NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(20) NOT NULL,
USERCODE VARCHAR(20) NOT NULL,
CONTRASEÑA VARCHAR(20) NOT NULL,
FEC_CREACION DATE NOT NULL,
PRIMARY KEY (ID_USUARIO));

CREATE TABLE ROLES (
ID_ROL DECIMAL(12) NOT NULL,
NOMBRE_ROL VARCHAR(20) NOT NULL,
PRIMARY KEY (ID_ROL));

CREATE TABLE ITEM (
ID_ITEM DECIMAL(12) NOT NULL,
ID_USUARIO DECIMAL(12) NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
VERSION VARCHAR(50) NOT NULL,
ESTADO DECIMAL(3) NOT NULL,
PRIORIDAD VARCHAR(10) NOT NULL,
OBSERVACIONES VARCHAR(50) NOT NULL,
FEC_INI DATE NOT NULL,
FEC_MOD DATE NOT NULL,
PRIMARY KEY (ID_ITEM),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO));

CREATE TABLE HISTORIAL_ITEM (
ID_ITEM DECIMAL(12) NOT NULL,
VERSION VARCHAR(50) NOT NULL,
ID_USUARIO DECIMAL(12) NOT NULL,
ESTADO DECIMAL(3) NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
OBSERVACIONES VARCHAR(50) NOT NULL,
FEC_INI DATE NOT NULL,
FEC_MOD DATE NOT NULL,
PRIMARY KEY (ID_ITEM),
FOREIGN KEY (ID_ITEM) REFERENCES ITEM(ID_ITEM),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO));

CREATE TABLE DETALLE_FASE (
TIPO_FASE DECIMAL(3) NOT NULL,
DESCRIPCION VARCHAR(20) NOT NULL,
PRIMARY KEY (TIPO_FASE));

CREATE TABLE PROYECTO (
ID_PROYECTO DECIMAL(12) NOT NULL,
ID_ROL DECIMAL(12) NOT NULL,
ID_USUARIO DECIMAL(12) NOT NULL,
ID_FASE DECIMAL(12) NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
ESTADO DECIMAL(3) NOT NULL,
FEC_INI DATE NOT NULL,
FEC_FIN DATE NOT NULL,
PRIMARY KEY (ID_PROYECTO),
FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO));

CREATE TABLE FASES (
ID_FASE DECIMAL(12) NOT NULL,
ID_PROYECTO DECIMAL(12) NOT NULL,
ID_LINEABASE DECIMAL(12),
ID_ITEM DECIMAL(12) NOT NULL,
TIPO_FASE DECIMAL(3) NOT NULL,
FEC_CREA DATE NOT NULL,
FEC_MOD DATE NOT NULL,
PRIMARY KEY (ID_FASE),
FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO(ID_PROYECTO),
FOREIGN KEY (ID_ITEM) REFERENCES ITEM(ID_ITEM),
FOREIGN KEY (TIPO_FASE) REFERENCES DETALLE_FASE(TIPO_FASE));

ALTER TABLE PROYECTO ADD FOREIGN KEY (ID_FASE) REFERENCES FASES(ID_FASE);

CREATE TABLE LINEA_BASE(
ID_LINEABASE DECIMAL(12) NOT NULL,
ID_FASE DECIMAL(12) NOT NULL,
ID_USUARIO DECIMAL(12) NOT NULL,
ESTADO DECIMAL(3) NOT NULL,
FEC_CREA DATE NOT NULL,
FEC_MOD DATE NOT NULL,
PRIMARY KEY(ID_LINEABASE),
FOREIGN KEY (ID_FASE) REFERENCES FASES(ID_FASE),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO));

ALTER TABLE FASES ADD FOREIGN KEY (ID_LINEABASE) REFERENCES LINEA_BASE(ID_LINEABASE);
